pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/PuaPau2023/selenium_project.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest --html=reports/test_report.html'
            }
        }
    }
}
