name: Selenium Tests

on: [push, pull_request]

jobs: 
   tests:
       runs-on: window-latest
       
       steps:
        -name: Install Dependencies
        run: pip install -r requirements.txt

        -name: Run Test
        run: python --html=reports/test_report.html 
